### PR TITLE
Added Flipp, Paytm, Veeva

### PR DESCRIPTION
**Pull request by shamamaz**
Added some companies with Canadian listings.

### CODE REVIEW

**Comment by shamamaz** [comment]
Hi! the Travis build is failing because of three other websites, flagging those issues. As far as I can tell, the links I added work, though.

**Comment by j-delaney** [comment]
Thanks for contributing! Could you please make sure the locations are sorted alphabetically?

**Comment by shamamaz** [comment]
@j-delaney updated the location lists to be in alphabetical order.

**Comment by j-delaney** [comment]
Thanks for the contribution :)

**Pull request merged**
