### PR TITLE
Add Acquia

### PR DESCRIPTION
**Pull request by askreet**

### CODE REVIEW

**Comment by j-delaney** [comment]
Thanks for opening this PR! Could you please update it so that the locations are in alphabetical order?

**Comment by j-delaney** [comment]
Ping @askreet

**Comment by askreet** [comment]
@j-delaney All set! Thanks.

**Comment by j-delaney** [comment]
Sorry, one more small change I need. Could you change "CAN" to "Canada"?

**Comment by askreet** [comment]
All set.

**Comment by j-delaney** [comment]
Thanks! I appreciate you taking the time to do all those revisions :)

**Pull request merged**
