### PR TITLE
added missing locations for all but one companies.

### PR DESCRIPTION
**Pull request by DannyMcwaves**
Added all missing locations except for 'The League' company.
Changed the the career page for 'The League company'.

### CODE REVIEW

**Comment by j-delaney** [comment]
This is awesome! Thanks a ton :) Could you please update it so that locations are in alphabetical order though?

**Comment by DannyMcwaves** [comment]
Yh sure. You got it.

**Comment by j-delaney** [comment]
Thanks!

**Comment by DannyMcwaves** [comment]
You welcome.
Would you consider a company that requires you to take a small 
challenge before you submit your application easy to apply to?
Let's say a software company.

**Pull request merged**
