### PR TITLE
Add IFTTT

### PR DESCRIPTION
**Pull request by nettofarah**
We're hiring! 😅

### CODE REVIEW

**Comment by j-delaney** [comment]
Thanks! Always happy to see another company with a great application process :)

**Comment by nettofarah** [comment]
@j-delaney happy to be part of the list :)

**Comment by piyushkhemka** [comment]
@nettofarah Are you hiring interns too?

**Comment by nettofarah** [comment]
@piyushkhemka Possibly! Hit us at jobs@ifttt.com :)

**Pull request merged**
