### PR TITLE
adds thoughtworks to the list, greenhouse FTW!

### PR DESCRIPTION
**Pull request by steffencrespo**
I didn't see my company there. We use greenhouse as well so it belongs to this list :D

### CODE REVIEW

**Comment by j-delaney** [comment]
Awesome! Since your company has so many locations, could you just change the location to "Worldwide"?

**Comment by steffencrespo** [comment]
Awesome suggestion, much better. Done!

**Comment by j-delaney** [comment]
Thanks for the fast response!

**Comment by steffencrespo** [comment]
You're welcome, thanks for the suggestion!

**Pull request merged**
