### PR TITLE
viewer with country filter

### PR DESCRIPTION
**Pull request by pankajpatel**
Simple viewer based on Readme.md data.

Just need to enable github pages for the repository.

### CODE REVIEW

**Comment by j-delaney** [comment]
This is awesome! Thanks a ton for doing this. I might be misunderstanding https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/ but it looks like the folder will need to be named `docs` instead of `viewer` for gh-pages to work

**Comment by j-delaney** [comment]
@pankajpatel It looks like the page isn't loading `README.md` properly. http://j-delaney.github.io/easy-application/

**Comment by pankajpatel** [comment]
Wait for a minute, as serving from /docs has its own problems

**Comment by j-delaney** [comment]
Another option is to do a GET request to https://raw.githubusercontent.com/j-delaney/easy-application/master/README.md

**Comment by j-delaney** [comment]
I switched it to use that hardcoded link and it works now. Thanks again for this! It will be really helpful

**Pull request merged**
