### PR TITLE
Added Flatiron, Tumblr, FiveStars, and Symphony

### PR DESCRIPTION
**Pull request by dsouzarc**
Added two new companies with easy applications.

Tumblr uses Greenhouse and Flatiron is just a few text fields

### CODE REVIEW

**Comment by dsouzarc** [comment]
FiveStars and Symphony also use Greenhouse

**Comment by j-delaney** [comment]
Thank you for your PR! Could you please make sure all the locations are in alphabetical order as well?

**Comment by dsouzarc** [comment]
@j-delaney Fixed it; I accidentally put Tinder in the wrong spot, but everything - including their locations - should now be in alphabetical order

**Comment by j-delaney** [comment]
Thanks for such a fast response! I appreciate you contributing more companies to the list :)

**Comment by dsouzarc** [comment]
Of course! This was an excellent idea and I applied to quite a few companies from this list, so thank you for that :)

**Pull request merged**
